### PR TITLE
Store

### PR DESCRIPTION
**Pull request by ldiez**
This entity Type models stores/shops in the city. The model is based on the one defined by [Schema.org](https://schema.org/Store). In particular, the model contains a subset of the properties defined in the mentioned link, and a list of store categories, that can be afterwards specialized as concrete Types (see [https://schema.org/Store](https://schema.org/Store)).

### CODE REVIEW

**Comment by albertoabellagarcia** [comment]
Several errors to be accepted this PR
1.- Schedule and opening hours does not meet the schema
2.- Missing examples in the README.md
3.- OpeningHoursSpecification $ref in  spec.md is empty
4.- openingHoursSpecification in example-normalized.json does not meet schema definition
5.- openingHoursSpecification in example.json does not meet schema definition
6.- example.jsonld is partially normalized and partially keyvalues (It should be keyvalues all)

**Comment by ldiez** [comment]
Thanks for the review. The last commit failed, I'm fixing the other issues. I have some doubts though. 

- 1.- Schedule and opening hours does not meet the schema
  - I guess you mean OpeningHoursSpecification, ok
- 2.- Missing examples in the README.md
  - It is because the commit failure, ok
- 3.- OpeningHoursSpecification $ref in spec.md is empty
  - How can reference the specification in [database](https://github.com/smart-data-models/data-models/blob/master/specs/AllSubjects/official_list_data_terms.json)? I have not found any example. I would also use it in the schema. 

- 4.- openingHoursSpecification in example-normalized.json does not meet schema definition
  - ok

- 5.- openingHoursSpecification in example.json does not meet schema definition
  - ok

- 6.- example.jsonld is partially normalized and partially keyvalues (It should be keyvalues all)
  - According to [template](https://github.com/smart-data-models/data-models/blob/master/templates/dataModel/example1.jsonld) it is not key-value, but normalized. Also, in other [examples](https://github.com/smart-data-models/pending/blob/1254499a343fad37f62fcef875c8c657e7ed0179/BuildingType/example.jsonld) some properties (source, dataProvider, entityVersion) are keyvalue. Is that correct?

**Comment by albertoabellagarcia** [comment]
comments on the payloads pending to be adapted

**Comment by albertoabellagarcia** [comment]
openingHoursSpecification already a master resource. Please include it by using this line
"$ref" : ""https://smart-data-models.github.io/data-models/common-schema.json#/definitions/DateTime-Commons""

**Comment by albertoabellagarcia** [comment]
solved the OpeningHoursSpecification,  with the general solution on the shared [commons-schema.json](https://github.com/smart-data-models/data-models/blob/master/common-schema.json)

**Review by albertoabellagarcia — COMMENTED** [review]
This approach to the README has been substituted for an automatic generation.

**Pull request closed without merging**
