### PR TITLE
Fixed broken yaml links in spec.md

### PR DESCRIPTION
**Pull request by ldiez**
Fixed broken links in spec.md referencing to YAML common definitions

### CODE REVIEW

**Comment by albertoabellagarcia** [comment]
Right two last fixes but the first one it just includes common section with the dateCreated and dateModified which is just internal attributesof NGSIv2.... possible but not clean. Furhter discussion mqayb on contents of ngsi-ld.yaml

**Comment by ldiez** [comment]
> 
> 
> Right two last fixes but the first one it just includes common section with the dateCreated and dateModified which is just internal attributesof NGSIv2.... possible but not clean. Furhter discussion mqayb on contents of ngsi-ld.yaml

It also includes `id` and `type` which would be fine anyway. I tend to think that it is an issue of the ngsi-ld.yaml file rather than of this model. Shall we remove the link for now from the model? Or keep it and create an issue about the ngsi-ld.yaml?

**Comment by albertoabellagarcia** [comment]
Processing contents ngsi-ld.yaml· it will take us a while.

**Review by albertoabellagarcia — COMMENTED** [review]
The errors were rightly detected but the new links were wrong.

**Comment by albertoabellagarcia** [comment]
a new PR directly implement it

**Review by albertoabellagarcia — COMMENTED** [review]
done, no more work needed

**Pull request closed without merging**
